sinniger_test_homepage:
    path:     /hello/{name}
    defaults: { _controller: SinnigerTestBundle:Default:index }

sinniger_test_form:
    path:     /form/
    defaults: { _controller: SinnigerTestBundle:Default:form }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"