parameters:
#    sinniger_test.example.class: Sinniger\TestBundle\Example

services:
#    sinniger_test.example:
#        class: %sinniger_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
