<?php

namespace Sinniger\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SprachenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprachenRepository extends EntityRepository
{
}
